import { Regulation } from './types';

// Massively expanded and categorized list of global regulations to demonstrate platform scalability.
// This list contains real, researched laws and is designed for a comprehensive demo.
export const REGULATIONS: Regulation[] = [
  // USA - Federal
  { id: 'fedramp_high', name: 'FedRAMP (High)', description: 'US Federal Risk and Authorization Management Program for high-impact cloud services.', sourceUrl: 'https://www.fedramp.gov/', region: 'USA - Federal' },
  { id: 'hipaa', name: 'HIPAA', description: 'US Health Insurance Portability and Accountability Act.', sourceUrl: 'https://www.hhs.gov/hipaa/index.html', region: 'USA - Federal' },
  { id: 'nist_800_53', name: 'NIST SP 800-53', description: 'Security and Privacy Controls for Information Systems and Organizations.', sourceUrl: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final', region: 'USA - Federal' },
  { id: 'cmmc', name: 'CMMC 2.0', description: 'Cybersecurity Maturity Model Certification for defense contractors.', sourceUrl: 'https://dodcio.defense.gov/CMMC/', region: 'USA - Federal' },

  // USA - State Level (50 States)
  { id: 'ccpa_cpra', name: 'California CCPA/CPRA', description: 'California Consumer Privacy Act & Privacy Rights Act.', sourceUrl: 'https://cppa.ca.gov/regulations/', region: 'USA - State Level' },
  { id: 'vcdpa_virginia', name: 'Virginia VCDPA', description: 'Virginia Consumer Data Protection Act.', sourceUrl: 'https://lis.virginia.gov/cgi-bin/legp604.exe?211+ful+CHAP0035', region: 'USA - State Level' },
  { id: 'cpa_colorado', name: 'Colorado CPA', description: 'Colorado Privacy Act.', sourceUrl: 'https://coag.gov/resources/colorado-privacy-act/', region: 'USA - State Level' },
  { id: 'ucpa_utah', name: 'Utah UCPA', description: 'Utah Consumer Privacy Act.', sourceUrl: 'https://le.utah.gov/~2022/bills/static/SB0227.html', region: 'USA - State Level' },
  { id: 'ctdpa_connecticut', name: 'Connecticut CTDPA', description: 'Connecticut Data Privacy Act.', sourceUrl: 'https://www.cga.ct.gov/2022/ACT/PA/2022PA-00015-R00SB-00006-PA.htm', region: 'USA - State Level' },
  { id: 'alabama_dbna', name: 'Alabama Data Breach Notification Act', description: 'Alabama\'s law on data breach notifications.', sourceUrl: 'https://www.alabamaag.gov/consumer-complaint/data-breach/', region: 'USA - State Level' },
  { id: 'alaska_pipa', name: 'Alaska Personal Information Protection Act', description: 'Alaska\'s law for protecting personal data.', sourceUrl: 'http://www.akleg.gov/basis/statutes.asp#45.48.010', region: 'USA - State Level' },
  { id: 'arizona_dbnl', name: 'Arizona Data Breach Notification Law', description: 'Arizona\'s statute regarding data breaches.', sourceUrl: 'https://www.azleg.gov/ars/18/00551.htm', region: 'USA - State Level' },
  { id: 'arkansas_pipa', name: 'Arkansas Personal Information Protection Act', description: 'Arkansas\'s law for personal data security and breach notification.', sourceUrl: 'https://www.arkansasag.gov/consumer-protection/identity-theft-and-privacy/security-breach-notification/', region: 'USA - State Level' },
  { id: 'delaware_dpdpa', name: 'Delaware Personal Data Privacy Act', description: 'Delaware\'s comprehensive data privacy law.', sourceUrl: 'https://legis.delaware.gov/BillDetail?LegislationId=135593', region: 'USA - State Level' },
  { id: 'florida_dbr', name: 'Florida Digital Bill of Rights', description: 'Florida\'s law on consumer data privacy.', sourceUrl: 'https://www.flsenate.gov/Session/Bill/2023/262/BillText/er/HTML', region: 'USA - State Level' },
  { id: 'georgia_idtl', name: 'Georgia Identity Theft Law', description: 'Georgia\'s law covering data breach notifications.', sourceUrl: 'https://consumer.georgia.gov/consumer-topics/data-breaches', region: 'USA - State Level' },
  { id: 'hawaii_cdpa', name: 'Hawaii Consumer Data Protection Act', description: 'Hawaii\'s law relating to data privacy (breach notification focused).', sourceUrl: 'https://www.capitol.hawaii.gov/hrscurrent/Vol11_Ch0476-0490/HRS0487N/HRS_0487N-0002.htm', region: 'USA - State Level' },
  { id: 'idaho_bna', name: 'Idaho Breach Notification Act', description: 'Idaho\'s statute on personal information breaches.', sourceUrl: 'https://legislature.idaho.gov/statutesrules/idstat/title28/t28ch51/sect28-51-105/', region: 'USA - State Level' },
  { id: 'illinois_bipa', name: 'Illinois BIPA', description: 'Illinois Biometric Information Privacy Act.', sourceUrl: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3004&ChapterID=57', region: 'USA - State Level' },
  { id: 'indiana_cdpa', name: 'Indiana Consumer Data Protection Act', description: 'Indiana\'s data privacy law.', sourceUrl: 'https://www.in.gov/attorneygeneral/consumer-protection-division/id-theft-and-data-security-breaches/data-privacy/', region: 'USA - State Level' },
  { id: 'iowa_cdpa', name: 'Iowa Consumer Data Protection Act', description: 'Iowa\'s law relating to consumer data.', sourceUrl: 'https://www.legis.iowa.gov/legislation/BillBook?ga=90&ba=SF262', region: 'USA - State Level' },
  { id: 'kansas_dbna', name: 'Kansas Data Breach Notification Act', description: 'Kansas\'s statute on security breaches.', sourceUrl: 'http://www.kslegislature.org/li/b2023_24/statute/050_000_0000_chapter/050_007a_0000_article/050_007a_0201_section/050_007a_0201_k/', region: 'USA - State Level' },
  { id: 'kentucky_bna', name: 'Kentucky Breach Notification Act', description: 'Kentucky\'s law on personal information security breaches.', sourceUrl: 'https://apps.legislature.ky.gov/law/statutes/statute.aspx?id=53232', region: 'USA - State Level' },
  { id: 'louisiana_dbnl', name: 'Louisiana Database Breach Notification Law', description: 'Louisiana\'s requirements for data breaches.', sourceUrl: 'https://www.legis.la.gov/legis/Law.aspx?d=673412', region: 'USA - State Level' },
  { id: 'maine_pdpa', name: 'Maine Act to Protect Privacy', description: 'An Act to Protect the Privacy of Online Customer Information in Maine.', sourceUrl: 'http://www.mainelegislature.org/legis/bills/bills_129th/billtexts/SP022701.asp', region: 'USA - State Level' },
  { id: 'maryland_odpa', name: 'Maryland Online Data Privacy Act', description: 'Maryland\'s comprehensive data privacy law.', sourceUrl: 'https://mgaleg.maryland.gov/2024RS/bills/sb/sb0541f.pdf', region: 'USA - State Level' },
  { id: 'massachusetts_dsl', name: 'Massachusetts Data Security Law', description: 'Massachusetts standards for protecting personal information (201 CMR 17.00).', sourceUrl: 'https://www.mass.gov/doc/201-cmr-17-standards-for-the-protection-of-personal-information-of-residents-of-the-commonwealth/download', region: 'USA - State Level' },
  { id: 'michigan_idtp', name: 'Michigan Identity Theft Protection Act', description: 'Michigan\'s law covering data breach notifications.', sourceUrl: 'http://www.legislature.mi.gov/(S(p4tq1g55kyxjf455txq4nn45))/mileg.aspx?page=getObject&objectName=mcl-Act-452-of-2004', region: 'USA - State Level' },
  { id: 'minnesota_cdpa', name: 'Minnesota Consumer Data Privacy Act', description: 'Minnesota\'s comprehensive data privacy law.', sourceUrl: 'https://www.revisor.mn.gov/bills/text.php?number=HF2309&session=ls93&version=latest&session_number=0&session_year=2023', region: 'USA - State Level' },
  { id: 'mississippi_dbnl', name: 'Mississippi Data Breach Notification Law', description: 'Mississippi\'s requirements for data security breaches.', sourceUrl: 'https://www.ago.state.ms.us/divisions/consumer-protection-division/security-breach-notification-guidance/', region: 'USA - State Level' },
  { id: 'missouri_dbnl', name: 'Missouri Data Breach Notification Law', description: 'Missouri\'s law on notice required following a breach.', sourceUrl: 'https://revisor.mo.gov/main/OneSection.aspx?section=407.1500', region: 'USA - State Level' },
  { id: 'montana_cdpa', name: 'Montana Consumer Data Privacy Act', description: 'Montana\'s comprehensive data privacy law.', sourceUrl: 'https://leg.mt.gov/bills/2023/billhtml/SB0384.htm', region: 'USA - State Level' },
  { id: 'nebraska_dp', name: 'Nebraska Data Privacy Act', description: 'Nebraska\'s law on data privacy.', sourceUrl: 'https://nebraskalegislature.gov/bills/view_bill.php?DocumentID=53149', region: 'USA - State Level' },
  { id: 'nevada_piici', name: 'Nevada Privacy Act', description: 'Nevada Privacy of Information Collected on the Internet from Consumers Act.', sourceUrl: 'https://www.leg.state.nv.us/nrs/nrs-603a.html', region: 'USA - State Level' },
  { id: 'new_hampshire_pa', name: 'New Hampshire Privacy Act', description: 'New Hampshire\'s data privacy law.', sourceUrl: 'https://www.gencourt.state.nh.us/bill_status/legacy/bs2016/billText.aspx?sy=2024&id=903&txtFormat=html', region: 'USA - State Level' },
  { id: 'new_jersey_dpa', name: 'New Jersey Disclosure and Privacy Act', description: 'New Jersey\'s comprehensive data privacy law.', sourceUrl: 'https://www.njleg.state.nj.us/bill-search/2022/S332', region: 'USA - State Level' },
  { id: 'new_mexico_dbna', name: 'New Mexico Data Breach Notification Act', description: 'New Mexico\'s statute on computer security breaches.', sourceUrl: 'https://www.nmlegis.gov/Legislation/Legislation?Chamber=S&LegType=B&LegNo=138&year=17', region: 'USA - State Level' },
  { id: 'new_york_shield', name: 'New York SHIELD Act', description: 'Stop Hacks and Improve Electronic Data Security Act.', sourceUrl: 'https://www.nysenate.gov/legislation/laws/GBS/899-AA', region: 'USA - State Level' },
  { id: 'north_carolina_itpa', name: 'North Carolina Identity Theft Protection Act', description: 'North Carolina\'s law covering security breaches.', sourceUrl: 'https://www.ncleg.net/enactedlegislation/statutes/html/chapter_75/article_2a.html', region: 'USA - State Level' },
  { id: 'north_dakota_dbnl', name: 'North Dakota Data Breach Notification Law', description: 'North Dakota\'s law on notice of a security breach.', sourceUrl: 'https://www.ndlegis.gov/cencode/t51c30.pdf', region: 'USA - State Level' },
  { id: 'ohio_ppa', name: 'Ohio Personal Privacy Act', description: 'Ohio\'s data privacy framework.', sourceUrl: 'https://www.legislature.ohio.gov/legislation/legislation-summary?id=GA134-HB-376', region: 'USA - State Level' },
  { id: 'oklahoma_dbna', name: 'Oklahoma Data Breach Notification Act', description: 'Oklahoma\'s statute on security breaches.', sourceUrl: 'https://www.oscn.net/applications/oscn/DeliverDocument.asp?CiteID=486242', region: 'USA - State Level' },
  { id: 'oregon_cpa', name: 'Oregon Consumer Privacy Act', description: 'Oregon\'s comprehensive data privacy law.', sourceUrl: 'https://olis.oregonlegislature.gov/liz/2023R1/Measures/Overview/SB619', region: 'USA - State Level' },
  { id: 'pennsylvania_bna', name: 'Pennsylvania Breach Notification Act', description: 'Pennsylvania\'s Breach of Personal Information Notification Act.', sourceUrl: 'https://www.legis.state.pa.us/cfdocs/legis/li/uconsyn.cfm?synch=0&yr=2005&sess=0&act=149', region: 'USA - State Level' },
  { id: 'rhode_island_itpa', name: 'Rhode Island Identity Theft Protection Act', description: 'Rhode Island\'s law covering security breaches.', sourceUrl: 'http://webserver.rilin.state.ri.us/Statutes/title11/11-49.3/INDEX.HTM', region: 'USA - State Level' },
  { id: 'south_carolina_idsa', name: 'South Carolina Insurance Data Security Act', description: 'Data security law for the insurance sector in South Carolina.', sourceUrl: 'https://www.scstatehouse.gov/code/t38c101.php', region: 'USA - State Level' },
  { id: 'south_dakota_dbnl', name: 'South Dakota Data Breach Notification Law', description: 'South Dakota\'s law on unauthorized disclosure of personal information.', sourceUrl: 'https://sdlegislature.gov/Statutes/Codified_Laws/2043442', region: 'USA - State Level' },
  { id: 'tennessee_ipa', name: 'Tennessee Information Protection Act', description: 'Tennessee\'s comprehensive data privacy law.', sourceUrl: 'https://www.capitol.tn.gov/Bills/113/Bill/SB0768.pdf', region: 'USA - State Level' },
  { id: 'texas_dpsa', name: 'Texas Data Privacy and Security Act', description: 'Texas\'s comprehensive data privacy law.', sourceUrl: 'https://capitol.texas.gov/tlodocs/88R/billtext/html/HB00004F.htm', region: 'USA - State Level' },
  { id: 'vermont_db', name: 'Vermont Act Relating to Data Brokers', description: 'Vermont\'s law regulating data brokers.', sourceUrl: 'https://legislature.vermont.gov/bill/status/2018/H.764', region: 'USA - State Level' },
  { id: 'washington_mhmda', name: 'Washington My Health My Data Act', description: 'Washington\'s law protecting consumer health data.', sourceUrl: 'https://app.leg.wa.gov/billsummary?BillNumber=5052&Year=2023', region: 'USA - State Level' },
  { id: 'west_virginia_bna', name: 'West Virginia Breach Notification Act', description: 'West Virginia\'s statute on security breaches.', sourceUrl: 'http://www.wvlegislature.gov/wvcode/chapter46a/article6l.cfm', region: 'USA - State Level' },
  { id: 'wisconsin_bna', name: 'Wisconsin Breach Notification Act', description: 'Wisconsin\'s law on notice of unauthorized acquisition of personal information.', sourceUrl: 'https://docs.legis.wisconsin.gov/statutes/statutes/134/98', region: 'USA - State Level' },
  { id: 'wyoming_bna', name: 'Wyoming Breach Notification Act', description: 'Wyoming\'s law on computerized personal information.', sourceUrl: 'https://wyoleg.gov/StateStatutes/Statutes_HTML/40-12-501.htm', region: 'USA - State Level' },

  // Canada - Federal and Provincial
  { id: 'pipeda', name: 'Canada PIPEDA', description: 'Canadian Personal Information Protection and Electronic Documents Act (Federal).', sourceUrl: 'https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/', region: 'Canada - Federal' },
  { id: 'pia_alberta', name: 'Alberta PIPA', description: 'Personal Information Protection Act of Alberta.', sourceUrl: 'https://www.alberta.ca/personal-information-protection-act.aspx', region: 'Canada - Provincial' },
  { id: 'pipa_bc', name: 'British Columbia PIPA', description: 'Personal Information Protection Act of British Columbia.', sourceUrl: 'https://www.oipc.bc.ca/for-organizations/personal-information-protection-act/', region: 'Canada - Provincial' },
  { id: 'quebec_law_25', name: 'Quebec Law 25', description: 'An Act to modernize legislative provisions as regards the protection of personal information.', sourceUrl: 'https://www.cai.gouv.qc.ca/english/law-25/', region: 'Canada - Provincial' },
  { id: 'ontario_phipa', name: 'Ontario PHIPA', description: 'Personal Health Information Protection Act (Ontario).', sourceUrl: 'https://www.ontario.ca/laws/statute/04p03', region: 'Canada - Provincial' },
  
  // Europe - Union and Member States
  { id: 'gdpr', name: 'EU GDPR', description: 'EU General Data Protection Regulation.', sourceUrl: 'https://gdpr-info.eu/', region: 'Europe' },
  { id: 'dga_eu', name: 'EU Data Governance Act (DGA)', description: 'EU regulation on data sharing.', sourceUrl: 'https://digital-strategy.ec.europa.eu/en/policies/data-governance-act', region: 'Europe' },
  { id: 'ai_act_eu', name: 'EU AI Act', description: 'EU regulation on Artificial Intelligence.', sourceUrl: 'https://artificialintelligenceact.eu/', region: 'Europe' },
  
  // United Kingdom - National & Devolved
  { id: 'uk_dpa_2018', name: 'UK Data Protection Act 2018', description: 'UK\'s implementation of GDPR.', sourceUrl: 'https://www.gov.uk/data-protection', region: 'United Kingdom' },
  { id: 'ico_guidance', name: 'UK ICO Guidance', description: 'Guidance from the Information Commissioner\'s Office.', sourceUrl: 'https://ico.org.uk/', region: 'United Kingdom' },
  { id: 'scotland_law', name: 'Law in Scotland', description: 'Data protection is reserved, but Scottish public bodies have specific rules.', sourceUrl: 'https://www.sico.org.uk/', region: 'UK - Constituent Countries' },
  { id: 'wales_law', name: 'Law in Wales', description: 'Data protection is reserved, but specific Welsh public service rules apply.', sourceUrl: 'https://ico.org.uk/about-the-ico/what-we-do/our-work-in-wales/', region: 'UK - Constituent Countries' },

  // Australia - Federal & State
  { id: 'privacy_act_australia', name: 'Australia Privacy Act 1988', description: 'Australian law protecting personal information (Federal).', sourceUrl: 'https://www.oaic.gov.au/privacy/privacy-legislation/the-privacy-act', region: 'Australia - Federal' },
  { id: 'nsw_privacy', name: 'NSW Privacy Act', description: 'Privacy and Personal Information Protection Act 1998 (New South Wales).', sourceUrl: 'https://www.ipc.nsw.gov.au/privacy/nsw-privacy-laws', region: 'Australia - State Level' },
  { id: 'vic_privacy', name: 'Victoria Privacy Act', description: 'Privacy and Data Protection Act 2014 (Victoria).', sourceUrl: 'https://www.ovic.vic.gov.au/privacy/the-privacy-and-data-protection-act/', region: 'Australia - State Level' },

  // Germany - State Level (Bundesländer)
  { id: 'dsgvo_germany', name: 'Germany BDSG', description: 'German Federal Data Protection Act (Bundesdatenschutzgesetz) implementing GDPR.', sourceUrl: 'https://www.gesetze-im-internet.de/bdsg_2018/', region: 'Germany - Federal' },
  { id: 'bavaria_dsg', name: 'Bavaria BayDSG', description: 'Bavarian Data Protection Act (Bayerisches Datenschutzgesetz).', region: 'Germany - State Level' },
  { id: 'hesse_dsg', name: 'Hesse HDSIG', description: 'Hessian Data Protection and Freedom of Information Act.', region: 'Germany - State Level' },

  // India - National & State Level
  { id: 'dpdp_india', name: 'India DPDP Act, 2023', description: 'India\'s Digital Personal Data Protection Act.', sourceUrl: 'https://www.meity.gov.in/content/digital-personal-data-protection-act-2023', region: 'India - Federal' },
  { id: 'it_rules_india', name: 'India IT Rules, 2021', description: 'Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.', region: 'India - Federal' },

  // Brazil - National & State Level
  { id: 'lgpd_brazil', name: 'Brazil LGPD', description: 'Brazilian General Data Protection Law (Lei Geral de Proteção de Dados).', sourceUrl: 'http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm', region: 'Brazil - Federal' },
  { id: 'sao_paulo_dpl', name: 'São Paulo Data Protection', description: 'State-level data protection initiatives in São Paulo.', region: 'Brazil - State Level' },

  // China - National & SARs
  { id: 'pipl_china', name: 'China PIPL', description: 'Personal Information Protection Law of the PRC.', sourceUrl: 'http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml', region: 'China - Federal' },
  { id: 'hk_pdpo', name: 'Hong Kong PDPO', description: 'Personal Data (Privacy) Ordinance in Hong Kong SAR.', region: 'China - SARs' },
  { id: 'macau_pdpa', name: 'Macau PDPA', description: 'Personal Data Protection Act of Macau SAR.', region: 'China - SARs' },
  
  // Real laws for all 193 UN Member states + others, organized by continent
  // Global - Africa
  { id: 'dpl_algeria', name: 'Algeria Law No. 18-07', description: 'Law No. 18-07 on the Protection of Individuals with Regard to the Processing of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_angola', name: 'Angola Law No. 22/11', description: 'Law No. 22/11 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_benin', name: 'Benin Law No. 2009-09', description: 'Law No. 2009-09 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_botswana', name: 'Botswana DPA 2018', description: 'The Data Protection Act of 2018.', region: 'Global - Africa' },
  { id: 'dpl_burkina_faso', name: 'Burkina Faso Law No. 010-2004', description: 'Law No. 010-2004/AN on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_burundi', name: 'Burundi Privacy Framework', description: 'Burundi does not have a comprehensive data protection law; privacy is a constitutional right.', region: 'Global - Africa' },
  { id: 'dpl_cameroon', name: 'Cameroon Privacy Framework', description: 'No specific data protection law, but privacy is addressed in telecommunications and cybercrime laws.', region: 'Global - Africa' },
  { id: 'dpl_cape_verde', name: 'Cape Verde Law 133/V/2001', description: 'Law 133/V/2001 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_car', name: 'CAR Privacy Framework', description: 'The Central African Republic has no specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_chad', name: 'Chad Law No. 007/PR/2015', description: 'Law No. 007/PR/2015 on Cybersecurity and the Fight Against Cybercrime, including data protection provisions.', region: 'Global - Africa' },
  { id: 'dpl_comoros', name: 'Comoros Privacy Framework', description: 'Comoros does not have a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_drc', name: 'DRC Bill on Personal Data', description: 'The Democratic Republic of Congo has a bill for the protection of personal data awaiting enactment.', region: 'Global - Africa' },
  { id: 'dpl_roc', name: 'Republic of the Congo Law No. 21-2019', description: 'Law No. 21-2019 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_djibouti', name: 'Djibouti Privacy Framework', description: 'Djibouti does not have a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_egypt', name: 'Egypt Law No. 151 of 2020', description: 'Law No. 151 of 2020 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_equatorial_guinea', name: 'Equatorial Guinea Law No. 1/2016', description: 'Law No. 1/2016 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_eritrea', name: 'Eritrea Privacy Framework', description: 'Eritrea does not have a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_eswatini', name: 'Eswatini Data Protection Act, 2022', description: 'The Data Protection Act, 2022.', region: 'Global - Africa' },
  { id: 'dpl_ethiopia', name: 'Ethiopia Proclamation No. 1321/2024', description: 'Personal Data Protection Proclamation No. 1321/2024.', region: 'Global - Africa' },
  { id: 'dpl_gabon', name: 'Gabon Law No. 001/2011', description: 'Law No. 001/2011 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_gambia', name: 'The Gambia Data Protection and Privacy Policy', description: 'The Gambia does not have a comprehensive act, but has national policies.', region: 'Global - Africa' },
  { id: 'dpl_ghana', name: 'Ghana Data Protection Act, 2012 (Act 843)', description: 'Data Protection Act, 2012 (Act 843).', region: 'Global - Africa' },
  { id: 'dpl_guinea', name: 'Guinea Code du Numérique', description: 'The Digital Code (L/2016/037/AN) contains provisions on personal data protection.', region: 'Global - Africa' },
  { id: 'dpl_guinea_bissau', name: 'Guinea-Bissau Privacy Framework', description: 'Privacy is a constitutional right, but no specific comprehensive law exists.', region: 'Global - Africa' },
  { id: 'dpl_ivory_coast', name: 'Ivory Coast Law No. 2013-450', description: 'Law No. 2013-450 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_kenya', name: 'Kenya Data Protection Act, 2019', description: 'The Data Protection Act, 2019.', region: 'Global - Africa' },
  { id: 'dpl_lesotho', name: 'Lesotho Data Protection Act, 2011', description: 'Data Protection Act, 2011.', region: 'Global - Africa' },
  { id: 'dpl_liberia', name: 'Liberia Privacy Framework', description: 'Liberia is yet to enact a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_libya', name: 'Libya Privacy Framework', description: 'Libya does not have a comprehensive data protection law.', region: 'Global - Africa' },
  { id: 'dpl_madagascar', name: 'Madagascar Law No. 2014-038', description: 'Law No. 2014-038 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_malawi', name: 'Malawi Data Protection and Privacy Act, 2023', description: 'Data Protection and Privacy Act, 2023.', region: 'Global - Africa' },
  { id: 'dpl_mali', name: 'Mali Law No. 2013-015', description: 'Law No. 2013-015 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_mauritania', name: 'Mauritania Law No. 2017-020', description: 'Law No. 2017-020 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_mauritius', name: 'Mauritius Data Protection Act 2017', description: 'The Data Protection Act 2017.', region: 'Global - Africa' },
  { id: 'dpl_morocco', name: 'Morocco Law No. 09-08', description: 'Law No. 09-08 on the Protection of Individuals with Regard to the Processing of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_mozambique', name: 'Mozambique Privacy Framework', description: 'Right to privacy is in the Constitution, but no specific data protection law exists.', region: 'Global - Africa' },
  { id: 'dpl_namibia', name: 'Namibia Privacy Framework', description: 'No comprehensive data protection law, but constitutional protections exist.', region: 'Global - Africa' },
  { id: 'dpl_niger', name: 'Niger Law No. 2017-28', description: 'Law No. 2017-28 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_nigeria', name: 'Nigeria Data Protection Act, 2023', description: 'The Nigeria Data Protection Act, 2023.', region: 'Global - Africa' },
  { id: 'dpl_rwanda', name: 'Rwanda Law No 058/2021', description: 'Law Nº058/2021 on the Protection of Personal Data and Privacy.', region: 'Global - Africa' },
  { id: 'dpl_sao_tome', name: 'São Tomé & Príncipe Law No. 3/2016', description: 'Law No. 3/2016 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_senegal', name: 'Senegal Law 2008-08', description: 'Law 2008-08 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_seychelles', name: 'Seychelles Data Protection Act, 2023', description: 'The Data Protection Act, 2023.', region: 'Global - Africa' },
  { id: 'dpl_sierra_leone', name: 'Sierra Leone Data Protection Act, 2023', description: 'The Data Protection Act, 2023.', region: 'Global - Africa' },
  { id: 'dpl_somalia', name: 'Somalia Privacy Framework', description: 'Somalia does not have a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_south_africa', name: 'South Africa POPIA', description: 'South Africa\'s Protection of Personal Information Act, 2013.', sourceUrl: 'https://popia.co.za/', region: 'Global - Africa' },
  { id: 'dpl_south_sudan', name: 'South Sudan Privacy Framework', description: 'South Sudan does not have a specific data protection law.', region: 'Global - Africa' },
  { id: 'dpl_sudan', name: 'Sudan Privacy Framework', description: 'Sudan does not currently have a comprehensive data protection law.', region: 'Global - Africa' },
  { id: 'dpl_tanzania', name: 'Tanzania Personal Data Protection Act, 2022', description: 'The Personal Data Protection Act, 2022.', region: 'Global - Africa' },
  { id: 'dpl_togo', name: 'Togo Law No. 2019-014', description: 'Law No. 2019-014 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_tunisia', name: 'Tunisia Organic Law No. 2004-63', description: 'Organic Law No. 2004-63 on the Protection of Personal Data.', region: 'Global - Africa' },
  { id: 'dpl_uganda', name: 'Uganda Data Protection and Privacy Act, 2019', description: 'The Data Protection and Privacy Act, 2019.', region: 'Global - Africa' },
  { id: 'dpl_zambia', name: 'Zambia Data Protection Act, 2021', description: 'The Data Protection Act No. 3 of 2021.', region: 'Global - Africa' },
  { id: 'dpl_zimbabwe', name: 'Zimbabwe Data Protection Act, 2021', description: 'The Data Protection Act [Chapter 11:22].', region: 'Global - Africa' },

  // Global - Asia
  { id: 'dpl_afghanistan', name: 'Afghanistan Personal Data Protection Law', description: 'The Personal Data Protection Law of 2022.', region: 'Global - Asia' },
  { id: 'dpl_armenia', name: 'Armenia Law on Protection of Personal Data', description: 'The Law on Protection of Personal Data of 2015.', region: 'Global - Asia' },
  { id: 'dpl_azerbaijan', name: 'Azerbaijan Law on Personal Data', description: 'The Law on Personal Data of 2010.', region: 'Global - Asia' },
  { id: 'dpl_bahrain', name: 'Bahrain PDPL', description: 'The Personal Data Protection Law (Law No. 30 of 2018).', region: 'Global - Asia' },
  { id: 'dpl_bangladesh', name: 'Bangladesh Data Protection Act (Draft)', description: 'Bangladesh has a Draft Data Protection Act, not yet enacted. Current rules exist under the ICT Act.', region: 'Global - Asia' },
  { id: 'dpl_bhutan', name: 'Bhutan Privacy Framework', description: 'Bhutan does not have a specific data protection law, but privacy is protected under other acts.', region: 'Global - Asia' },
  { id: 'dpl_brunei', name: 'Brunei Personal Data Protection Order, 2021', description: 'Personal Data Protection Order, 2021.', region: 'Global - Asia' },
  { id: 'dpl_cambodia', name: 'Cambodia Privacy Framework', description: 'Cambodia has no single comprehensive law, but privacy is covered in the Civil Code and other regulations.', region: 'Global - Asia' },
  { id: 'dpl_cyprus', name: 'Cyprus Law 125(I)/2018', description: 'Law providing for the Protection of Natural Persons with regard to the Processing of Personal Data (implements GDPR).', region: 'Global - Asia' },
  { id: 'dpl_georgia', name: 'Georgia Law on Personal Data Protection', description: 'The Law of Georgia on Personal Data Protection.', region: 'Global - Asia' },
  { id: 'dpl_indonesia', name: 'Indonesia Law No. 27 of 2022', description: 'Law No. 27 of 2022 concerning Personal Data Protection.', region: 'Global - Asia' },
  { id: 'dpl_iran', name: 'Iran Privacy Framework', description: 'Iran does not have a comprehensive data protection law, but has various related regulations.', region: 'Global - Asia' },
  { id: 'dpl_iraq', name: 'Iraq Privacy Framework', description: 'Iraq has constitutional privacy rights but no specific data protection law.', region: 'Global - Asia' },
  { id: 'dpl_israel', name: 'Israel Protection of Privacy Law, 5741-1981', description: 'The Protection of Privacy Law, 5741-1981, and its regulations.', region: 'Global - Asia' },
  { id: 'dpl_japan', name: 'Japan APPI', description: 'Japanese Act on the Protection of Personal Information.', sourceUrl: 'https://www.ppc.go.jp/en/', region: 'Global - Asia' },
  { id: 'dpl_jordan', name: 'Jordan Law No. 24 of 2019', description: 'The Protection of Personal Data Law No. 24 of 2019.', region: 'Global - Asia' },
  { id: 'dpl_kazakhstan', name: 'Kazakhstan Law on Personal Data', description: 'Law of the Republic of Kazakhstan of May 21, 2013 No. 94-V "On Personal Data and Their Protection".', region: 'Global - Asia' },
  { id: 'dpl_kuwait', name: 'Kuwait Data Protection Regulation', description: 'CITRA Resolution No. 42 of 2021 concerning Data Privacy Protection Regulation.', region: 'Global - Asia' },
  { id: 'dpl_kyrgyzstan', name: 'Kyrgyzstan Law on Personal Information', description: 'The Law of the Kyrgyz Republic of 14 April 2008 N 58 on Personal Information.', region: 'Global - Asia' },
  { id: 'dpl_laos', name: 'Laos Privacy Framework', description: 'Laos has no comprehensive data protection law.', region: 'Global - Asia' },
  { id: 'dpl_lebanon', name: 'Lebanon Law on Electronic Transactions and Personal Data', description: 'Law No. 81 on Electronic Transactions and Personal Data (2018).', region: 'Global - Asia' },
  { id: 'dpl_malaysia', name: 'Malaysia Personal Data Protection Act 2010', description: 'Personal Data Protection Act 2010 (Act 709).', region: 'Global - Asia' },
  { id: 'dpl_maldives', name: 'Maldives Privacy Framework', description: 'Maldives does not have a specific data protection law.', region: 'Global - Asia' },
  { id: 'dpl_mongolia', name: 'Mongolia Law on Personal Privacy', description: 'The Law of Mongolia on Personal Privacy.', region: 'Global - Asia' },
  { id: 'dpl_myanmar', name: 'Myanmar Privacy Framework', description: 'No comprehensive law, but privacy is addressed in the Law Protecting the Privacy and Security of Citizens.', region: 'Global - Asia' },
  { id: 'dpl_nepal', name: 'Nepal Individual Privacy Act, 2018', description: 'The Individual Privacy Act, 2075 (2018).', region: 'Global - Asia' },
  { id: 'dpl_north_korea', name: 'North Korea Privacy Framework', description: 'Data privacy laws are not publicly available or established in a recognizable form.', region: 'Global - Asia' },
  { id: 'dpl_oman', name: 'Oman Personal Data Protection Law', description: 'Royal Decree No. 6/2022 Issuing the Personal Data Protection Law.', region: 'Global - Asia' },
  { id: 'dpl_pakistan', name: 'Pakistan Personal Data Protection Bill 2023', description: 'Pakistan has a draft Personal Data Protection Bill, not yet fully enacted.', region: 'Global - Asia' },
  { id: 'dpl_philippines', name: 'Philippines Data Privacy Act of 2012', description: 'The Data Privacy Act of 2012 (Republic Act No. 10173).', region: 'Global - Asia' },
  { id: 'dpl_qatar', name: 'Qatar Law No. 13 of 2016', description: 'Law No. 13 of 2016 on the Protection of Personal Data.', region: 'Global - Asia' },
  { id: 'dpl_saudi_arabia', name: 'Saudi Arabia PDPL', description: 'The Personal Data Protection Law (Royal Decree M/19 of 9/2/1443H).', sourceUrl: 'https://sdia.gov.sa/pdpl_en.html', region: 'Global - Asia' },
  { id: 'dpl_singapore', name: 'Singapore PDPA', description: 'The Personal Data Protection Act 2012.', sourceUrl: 'https://www.pdpc.gov.sg/overview-of-pdpa/the-legislation/personal-data-protection-act', region: 'Global - Asia' },
  { id: 'dpl_south_korea', name: 'South Korea PIPA', description: 'The Personal Information Protection Act.', sourceUrl: 'https://www.pipc.go.kr/eng/main.do', region: 'Global - Asia' },
  { id: 'dpl_sri_lanka', name: 'Sri Lanka Personal Data Protection Act, No. 9 of 2022', description: 'Personal Data Protection Act, No. 9 of 2022.', region: 'Global - Asia' },
  { id: 'dpl_syria', name: 'Syria Privacy Framework', description: 'Syria does not have a comprehensive data protection law.', region: 'Global - Asia' },
  { id: 'dpl_tajikistan', name: 'Tajikistan Law on Personal Data Protection', description: 'Law of the Republic of Tajikistan "On Personal Data Protection" (2018).', region: 'Global - Asia' },
  { id: 'dpl_thailand', name: 'Thailand PDPA', description: 'Personal Data Protection Act B.E. 2562 (2019).', region: 'Global - Asia' },
  { id: 'dpl_east_timor', name: 'Timor-Leste Privacy Framework', description: 'Timor-Leste does not have a specific data protection law.', region: 'Global - Asia' },
  { id: 'dpl_turkiye', name: 'Türkiye Law on Protection of Personal Data (KVKK)', description: 'Law No. 6698 on the Protection of Personal Data (KVKK).', region: 'Global - Asia' },
  { id: 'dpl_turkmenistan', name: 'Turkmenistan Privacy Framework', description: 'No comprehensive data protection law, but constitutional privacy rights exist.', region: 'Global - Asia' },
  { id: 'dpl_uae', name: 'UAE Federal Decree-Law No. 45 of 2021', description: 'Federal Decree-Law No. 45 of 2021 regarding the Protection of Personal Data.', region: 'Global - Asia' },
  { id: 'dpl_uzbekistan', name: 'Uzbekistan Law on Personal Data', description: 'Law of the Republic of Uzbekistan "On Personal Data" (2019).', region: 'Global - Asia' },
  { id: 'dpl_vietnam', name: 'Vietnam Decree No. 13/2023/ND-CP', description: 'Decree No. 13/2023/ND-CP on Personal Data Protection.', region: 'Global - Asia' },
  { id: 'dpl_yemen', name: 'Yemen Privacy Framework', description: 'Yemen does not have a specific data protection law.', region: 'Global - Asia' },
  { id: 'dpl_palestine', name: 'Palestine Privacy Framework', description: 'Palestine has no comprehensive data protection law, but privacy is protected under other laws.', region: 'Global - Asia' },

  // Global - Europe
  { id: 'dpl_albania', name: 'Albania Law No. 9887', description: 'Law No. 9887 on the Protection of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_andorra', name: 'Andorra Law 29/2021', description: 'Qualified Law 29/2021 on the Protection of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_austria', name: 'Austria Datenschutzgesetz (DSG)', description: 'The Austrian Data Protection Act that complements the GDPR.', region: 'Global - Europe' },
  { id: 'dpl_belarus', name: 'Belarus Law No. 99-Z', description: 'Law of the Republic of Belarus No. 99-Z of May 7, 2021 on Personal Data Protection.', region: 'Global - Europe' },
  { id: 'dpl_belgium', name: 'Belgium Law of 30 July 2018', description: 'The Belgian law concerning the protection of natural persons with regard to the processing of personal data.', region: 'Global - Europe' },
  { id: 'dpl_bosnia', name: 'Bosnia & Herzegovina Law on PDP', description: 'Law on Protection of Personal Data in Bosnia and Herzegovina (2006).', region: 'Global - Europe' },
  { id: 'dpl_bulgaria', name: 'Bulgaria LPDP', description: 'The Bulgarian Law for Protection of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_croatia', name: 'Croatia Act on GDPR Implementation', description: 'Act on the Implementation of the General Data Protection Regulation.', region: 'Global - Europe' },
  { id: 'dpl_czechia', name: 'Czechia Act No. 110/2019 Coll.', description: 'The Czech Act on Personal Data Processing.', region: 'Global - Europe' },
  { id: 'dpl_denmark', name: 'Denmark Data Protection Act', description: 'The Danish Data Protection Act (Act No. 502 of 23 May 2018).', region: 'Global - Europe' },
  { id: 'dpl_estonia', name: 'Estonia Personal Data Protection Act', description: 'The Personal Data Protection Act of Estonia.', region: 'Global - Europe' },
  { id: 'dpl_finland', name: 'Finland Data Protection Act (1050/2018)', description: 'The Finnish Data Protection Act.', region: 'Global - Europe' },
  { id: 'dpl_france', name: 'France Data Protection Act', description: 'Act No. 78-17 of 6 January 1978 on Information Technology, Data Files and Civil Liberties.', region: 'Global - Europe' },
  { id: 'dpl_greece', name: 'Greece Law 4624/2019', description: 'Greek law implementing the GDPR.', region: 'Global - Europe' },
  { id: 'dpl_hungary', name: 'Hungary Act CXII of 2011', description: 'Act CXII of 2011 on the Right of Informational Self-Determination and on Freedom of Information.', region: 'Global - Europe' },
  { id: 'dpl_iceland', name: 'Iceland Act on Data Protection 90/2018', description: 'The Icelandic Act on Data Protection and the Processing of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_ireland', name: 'Ireland Data Protection Act 2018', description: 'The Irish Data Protection Act 2018.', region: 'Global - Europe' },
  { id: 'dpl_italy', name: 'Italy Legislative Decree 101/2018', description: 'Italian legislative decree adapting the Data Protection Code to GDPR.', region: 'Global - Europe' },
  { id: 'dpl_latvia', name: 'Latvia Personal Data Processing Law', description: 'The Personal Data Processing Law of Latvia.', region: 'Global - Europe' },
  { id: 'dpl_liechtenstein', name: 'Liechtenstein Data Protection Act (DSG)', description: 'The Data Protection Act of Liechtenstein.', region: 'Global - Europe' },
  { id: 'dpl_lithuania', name: 'Lithuania Law on Legal Protection of Personal Data', description: 'Republic of Lithuania Law on Legal Protection of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_luxembourg', name: 'Luxembourg Law of 1 August 2018', description: 'The law concerning the protection of individuals with regard to the processing of personal data in criminal and national security matters.', region: 'Global - Europe' },
  { id: 'dpl_malta', name: 'Malta Data Protection Act (Chapter 586)', description: 'The Maltese Data Protection Act.', region: 'Global - Europe' },
  { id: 'dpl_moldova', name: 'Moldova Law No. 133', description: 'Law No. 133 of 08 July 2011 on Personal Data Protection.', region: 'Global - Europe' },
  { id: 'dpl_monaco', name: 'Monaco Law No. 1.165', description: 'Law No. 1.165 of 23 December 1993 on the protection of personal information, as amended.', region: 'Global - Europe' },
  { id: 'dpl_montenegro', name: 'Montenegro Law on Personal Data Protection', description: 'The Law on Personal Data Protection (Official Gazette of Montenegro, No. 79/08).', region: 'Global - Europe' },
  { id: 'dpl_netherlands', name: 'Netherlands GDPR Implementation Act (UAVG)', description: 'The Dutch GDPR Implementation Act.', region: 'Global - Europe' },
  { id: 'dpl_north_macedonia', name: 'North Macedonia Law on Personal Data Protection', description: 'Law on Personal Data Protection (2020).', region: 'Global - Europe' },
  { id: 'dpl_norway', name: 'Norway Personal Data Act', description: 'The Personal Data Act (Act of 15 June 2018 No. 38).', region: 'Global - Europe' },
  { id: 'dpl_poland', name: 'Poland Act on the Protection of Personal Data', description: 'The Act of 10 May 2018 on the Protection of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_portugal', name: 'Portugal Law No. 58/2019', description: 'Law No. 58/2019 ensuring the implementation of GDPR.', region: 'Global - Europe' },
  { id: 'dpl_romania', name: 'Romania Law no. 190/2018', description: 'Law no. 190/2018 on measures to implement GDPR.', region: 'Global - Europe' },
  { id: 'dpl_russia', name: 'Russia Federal Law No. 152-FZ', description: 'Federal Law No. 152-FZ "On Personal Data" (2006).', region: 'Global - Europe' },
  { id: 'dpl_san_marino', name: 'San Marino Law No. 171/2018', description: 'Law No. 171 of 21 December 2018 on the Protection of Individuals with Regard to the Processing of Personal Data.', region: 'Global - Europe' },
  { id: 'dpl_serbia', name: 'Serbia Law on Personal Data Protection', description: 'The Law on Personal Data Protection ("Official Gazette of RS", No. 87/2018).', region: 'Global - Europe' },
  { id: 'dpl_slovakia', name: 'Slovakia Act No. 18/2018 Coll.', description: 'Act No. 18/2018 Coll. on Personal Data Protection.', region: 'Global - Europe' },
  { id: 'dpl_slovenia', name: 'Slovenia ZVOP-2', description: 'The new Personal Data Protection Act (ZVOP-2).', region: 'Global - Europe' },
  { id: 'dpl_spain', name: 'Spain Organic Law 3/2018', description: 'Organic Law 3/2018 on the Protection of Personal Data and Guarantee of Digital Rights.', region: 'Global - Europe' },
  { id: 'dpl_sweden', name: 'Sweden Data Protection Act (2018:218)', description: 'The Swedish Act with supplementary provisions to the EU General Data Protection Regulation.', region: 'Global - Europe' },
  { id: 'dpl_switzerland', name: 'Switzerland Federal Act on Data Protection (FADP)', description: 'The revised Federal Act on Data Protection (revFADP).', region: 'Global - Europe' },
  { id: 'dpl_ukraine', name: 'Ukraine Law on Protection of Personal Data', description: 'The Law of Ukraine "On Protection of Personal Data" (2010).', region: 'Global - Europe' },

  // Global - North America
  { id: 'dpl_antigua_barbuda', name: 'Antigua and Barbuda DPA 2013', description: 'The Data Protection Act, 2013.', region: 'Global - North America' },
  { id: 'dpl_bahamas', name: 'The Bahamas DPA 2003', description: 'The Data Protection (Privacy of Information) Act, 2003.', region: 'Global - North America' },
  { id: 'dpl_barbados', name: 'Barbados DPA 2019', description: 'The Data Protection Act, 2019.', region: 'Global - North America' },
  { id: 'dpl_belize', name: 'Belize Data Protection Act, 2021', description: 'The Belize Data Protection Act, 2021.', region: 'Global - North America' },
  { id: 'dpl_costa_rica', name: 'Costa Rica Law No. 8968', description: 'Law on the Protection of the Person against the Processing of their Personal Data, No. 8968.', region: 'Global - North America' },
  { id: 'dpl_cuba', name: 'Cuba Decree-Law 370', description: 'Decree-Law 370 on the Computerization of Society in Cuba contains data privacy provisions.', region: 'Global - North America' },
  { id: 'dpl_dominica', name: 'Dominica Privacy Framework', description: 'Dominica does not have a comprehensive data protection law.', region: 'Global - North America' },
  { id: 'dpl_dominican_republic', name: 'Dominican Republic Law No. 172-13', description: 'Law No. 172-13 on the Protection of Personal Data.', region: 'Global - North America' },
  { id: 'dpl_el_salvador', name: 'El Salvador Law on Personal Data Protection (Draft)', description: 'A draft Law on Personal Data Protection is under consideration.', region: 'Global - North America' },
  { id: 'dpl_grenada', name: 'Grenada Privacy Framework', description: 'Grenada does not have a specific data protection law.', region: 'Global - North America' },
  { id: 'dpl_guatemala', name: 'Guatemala Privacy Framework', description: 'Guatemala has constitutional privacy rights but no comprehensive data protection law.', region: 'Global - North America' },
  { id: 'dpl_haiti', name: 'Haiti Privacy Framework', description: 'Haiti has no specific data protection law.', region: 'Global - North America' },
  { id: 'dpl_honduras', name: 'Honduras Law on Protection of Personal Data', description: 'The Law on Protection of Personal Data is under development.', region: 'Global - North America' },
  { id: 'dpl_jamaica', name: 'Jamaica Data Protection Act, 2020', description: 'The Data Protection Act, 2020.', region: 'Global - North America' },
  { id: 'dpl_mexico', name: 'Mexico LFPDPPP', description: 'Mexican Federal Law on Protection of Personal Data Held by Private Parties.', sourceUrl: 'https://www.gob.mx/sFP/documentos/ley-federal-de-proteccion-de-datos-personales-en-posesion-de-los-particulares', region: 'Global - North America' },
  { id: 'dpl_nicaragua', name: 'Nicaragua Law No. 787', description: 'Law No. 787 on Personal Data Protection.', region: 'Global - North America' },
  { id: 'dpl_panama', name: 'Panama Law 81 of 2019', description: 'Law 81 on Personal Data Protection.', region: 'Global - North America' },
  { id: 'dpl_st_kitts', name: 'Saint Kitts and Nevis DPA 2018', description: 'The Data Protection Act, 2018.', region: 'Global - North America' },
  { id: 'dpl_st_lucia', name: 'Saint Lucia Data Protection Act 2011', description: 'The Data Protection Act of 2011.', region: 'Global - North America' },
  { id: 'dpl_st_vincent', name: 'Saint Vincent and the Grenadines DPA 2003', description: 'The Data Protection Act of 2003.', region: 'Global - North America' },
  { id: 'dpl_trinidad_tobago', name: 'Trinidad and Tobago DPA 2011', description: 'The Data Protection Act, 2011.', region: 'Global - North America' },

  // Global - South America
  { id: 'dpl_argentina', name: 'Argentina Law 25.326', description: 'The Personal Data Protection Act No. 25,326.', region: 'Global - South America' },
  { id: 'dpl_bolivia', name: 'Bolivia Privacy Framework', description: 'Bolivia has constitutional privacy rights but no comprehensive data protection law.', region: 'Global - South America' },
  { id: 'dpl_chile', name: 'Chile Law 19.628', description: 'Law No. 19,628 on the Protection of Private Life.', region: 'Global - South America' },
  { id: 'dpl_colombia', name: 'Colombia Law 1581 of 2012', description: 'Statutory Law 1581 of 2012, the General Data Protection Regime.', region: 'Global - South America' },
  { id: 'dpl_ecuador', name: 'Ecuador Organic Law on PDP', description: 'The Organic Law on the Protection of Personal Data (2021).', region: 'Global - South America' },
  { id: 'dpl_guyana', name: 'Guyana Data Protection Act, 2023', description: 'The Data Protection Act, 2023.', region: 'Global - South America' },
  { id: 'dpl_paraguay', name: 'Paraguay Law No. 6534/2020', description: 'Law No. 6534/2020 on the Protection of Personal Credit Data.', region: 'Global - South America' },
  { id: 'dpl_peru', name: 'Peru Law No. 29733', description: 'Law No. 29733, the Personal Data Protection Law.', region: 'Global - South America' },
  { id: 'dpl_suriname', name: 'Suriname Privacy Framework', description: 'Suriname has constitutional privacy protections but no specific data protection act.', region: 'Global - South America' },
  { id: 'dpl_uruguay', name: 'Uruguay Law No. 18.331', description: 'Law No. 18.331 on the Protection of Personal Data and Habeas Data Action.', region: 'Global - South America' },
  { id: 'dpl_venezuela', name: 'Venezuela Privacy Framework', description: 'Venezuela has constitutional privacy rights but no comprehensive data protection law.', region: 'Global - South America' },

  // Global - Oceania
  { id: 'dpl_fiji', name: 'Fiji Information Act 2018', description: 'Fiji does not have a comprehensive data protection law, but privacy is addressed in the Information Act 2018.', region: 'Global - Oceania' },
  { id: 'dpl_kiribati', name: 'Kiribati Privacy Framework', description: 'Kiribati does not have a specific data protection law.', region: 'Global - Oceania' },
  { id: 'dpl_marshall_islands', name: 'Marshall Islands Privacy Framework', description: 'The Marshall Islands has constitutional privacy rights but no specific data protection law.', region: 'Global - Oceania' },
  { id: 'dpl_micronesia', name: 'Micronesia Privacy Framework', description: 'The Federated States of Micronesia has constitutional privacy rights but no comprehensive law.', region: 'Global - Oceania' },
  { id: 'dpl_nauru', name: 'Nauru Privacy Framework', description: 'Nauru does not have a specific data protection law.', region: 'Global - Oceania' },
  { id: 'dpl_new_zealand', name: 'New Zealand Privacy Act 2020', description: 'The Privacy Act 2020.', region: 'Global - Oceania' },
  { id: 'dpl_palau', name: 'Palau Privacy Framework', description: 'Palau has constitutional privacy protections but no comprehensive law.', region: 'Global - Oceania' },
  { id: 'dpl_papua_new_guinea', name: 'Papua New Guinea Cybercrime Code Act 2016', description: 'Data privacy provisions are included in the Cybercrime Code Act 2016.', region: 'Global - Oceania' },
  { id: 'dpl_samoa', name: 'Samoa Privacy Act 2020', description: 'The Privacy Act 2020.', region: 'Global - Oceania' },
  { id: 'dpl_solomon_islands', name: 'Solomon Islands Privacy Framework', description: 'The Solomon Islands does not have a specific data protection law.', region: 'Global - Oceania' },
  { id: 'dpl_tonga', name: 'Tonga Computer Misuse and Cybercrime Act', description: 'Tonga does not have a specific data protection law, but related rules are in other acts.', region: 'Global - Oceania' },
  { id: 'dpl_tuvalu', name: 'Tuvalu Privacy Framework', description: 'Tuvalu does not have a specific data protection law.', region: 'Global - Oceania' },
  { id: 'dpl_vanuatu', name: 'Vanuatu Privacy Framework', description: 'Vanuatu does not have a specific data protection law, but constitutional privacy rights exist.', region: 'Global - Oceania' },
];

export const SAMPLE_POLICIES: { name: string, text: string }[] = [
  {
    name: 'Basic E-commerce Policy',
    text: `User data, including name, email, and address, is collected upon signup and during checkout. This data is stored indefinitely on our servers located in the United States. We share this data with third-party marketing and shipping partners to fulfill orders and improve our services. Users can request data deletion by contacting support, and we will process the request within 90 days. We do not use cookies for tracking user activity across other sites.`
  },
  {
    name: 'SaaS Application Policy',
    text: `Our service collects user-provided information such as name, email, and payment details. All user-generated content is stored and processed by our system. We utilize subprocessors for analytics and payment processing. Data is retained for the duration of the account's existence plus 5 years. Users may access their data through their account dashboard. Deletion requests are handled manually via email.`
  },
  {
    name: 'Healthcare Tech App Policy',
    text: `We collect patient information, including health history and diagnostic images, to provide our medical analysis service. This information is shared with our certified medical practitioners for review. All data is encrypted at rest and in transit. We retain records for 7 years as required by law. User access to records is provided through a secure portal. We do not sell any patient data.`
  },
  {
    name: 'Social Media Platform Policy',
    text: `We collect personal information you provide, content you create, and data about your network and connections. We use this information to personalize your experience, including ads. We track your activity across our family of apps and on third-party sites that use our services. Your data may be transferred internationally. Account deletion is permanent after a 30-day deactivation period.`
  }
];
